name: Python Script Workflow

on:
  push:
    branches:
      - pyFlexSerial

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.12"

      - name: Install Dependencies
        run: pip install pyside6 pyserial

      - name: Create empty QML to omit bug
        run: touch empty.qml

      - name: Run Python Script
        run: pyside6-deploy -c pysidedeploy.spec

      - uses: actions/upload-artifact@v3
        with:
          name: pyFlexSerial
          path: ./pyflexserial
